### PR TITLE
make it actually boot by lowercasing the .PNG files

### PR DESCRIPTION
**Pull request by OtterCodes102**

### CODE REVIEW

**Comment by wxnnvs** [comment]
this project seems fake af

**Comment by OtterCodes102** [comment]
> this project seems fake af

ik

**Comment by btplayzxgit** [comment]
its not fake

**Comment by btplayzxgit** [comment]
trust

**Comment by wxnnvs** [comment]
Merge this then

**Comment by btplayzxgit** [comment]
why merge this

**Comment by wxnnvs** [comment]
It fixes

**Comment by btplayzxgit** [comment]
it fixes what?!?!?!?!

**Comment by btplayzxgit** [comment]
what does this fixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by OtterCodes102** [comment]
when you attempt to launch the game, it throws errors about files not existing, however this error does not show on Windows systems since their file system is case insensitive.

**Comment by btplayzxgit** [comment]
ok ill merge

**Comment by btplayzxgit** [comment]
ill merge it laterr

**Comment by OtterCodes102** [comment]
want me to help fix the merge issues?

**Comment by btplayzxgit** [comment]
wdym

**Comment by btplayzxgit** [comment]
oh merge issues? sure

**Review by btplayzxgit — COMMENTED** [review]
cool

**Comment by btplayzxgit** [comment]
its not letting me merge!!!!!!!!

**Comment by OtterCodes102** [comment]
you can merge now

**Comment by btplayzxgit** [comment]
wait

**Comment by btplayzxgit** [comment]
ive already fixed it lol

**Comment by btplayzxgit** [comment]
btw otter thx for pointing this out

**Comment by btplayzxgit** [comment]
otter can you tell the discord that my disc account is disabled?

**Comment by btplayzxgit** [comment]
lets close this PR up

**Pull request closed without merging**
