### PR TITLE
:trollface: how about pull request this

### PR DESCRIPTION
**Pull request by Orphanlol**

### CODE REVIEW

**Comment by btplayzxgit** [comment]
this is the guy who is making fake eaglercraft 1.9.4

**Comment by Orphanlol** [comment]
who

**Comment by btplayzxgit** [comment]
you

**Comment by Orphanlol** [comment]
https://github.com/developer-lfierrro743/ is the person who made fake eaglercraft

**Comment by btplayzxgit** [comment]
then why are you a contributor?

**Comment by btplayzxgit** [comment]
btw this is not eagler 1.8.8

**Comment by btplayzxgit** [comment]
and i didnt put eagtek 2.0, my friend did, this was supposed to be eagler 1.20 until dmca

**Comment by Orphanlol** [comment]
> then why are you a contributor?

when i was a wee dumbass i put real code and then realized the owner was a retarded asshole

**Comment by Orphanlol** [comment]
also you banned me from joining Klockcraft

**Comment by btplayzxgit** [comment]
wdym

**Comment by btplayzxgit** [comment]
the link has expired and my discord account is disabled

**Comment by Orphanlol** [comment]
well merge it anyway

**Comment by btplayzxgit** [comment]
no im not merging this

**Comment by btplayzxgit** [comment]
well what now

**Comment by Orphanlol** [comment]
pull request the new one

**Comment by Orphanlol** [comment]
well i could help with assets

**Comment by btplayzxgit** [comment]
ok

**Pull request closed without merging**
