### PR TITLE
um actually

### PR DESCRIPTION
**Pull request by Orphanlol**

### CODE REVIEW

**Comment by btplayzxgit** [comment]
i got rid of the pets system

**Comment by btplayzxgit** [comment]
i got rid of it 1 week ago

**Comment by btplayzxgit** [comment]
wait ill brb

**Comment by Orphanlol** [comment]
might as well put ur email incase Mojang actually dmcas this, though that'd be stupid as there isn't any real functionality

**Comment by Orphanlol** [comment]
https://sites.google.com/view/klockcraft/why

**Comment by btplayzxgit** [comment]
what is it

**Comment by Orphanlol** [comment]
im not maintaining this, some guy named Denied2023 made you a chat skidding my chat. tell him to stop.
he posted it at sites.google.com/view/klockcraftmc.

**Pull request closed without merging**
